const mongodb = [
    {
        "_id" : "5d21551fed08ae87360b476e",
        "ignoredChats" : [],
        "acceptedChats" : [],
        "pendingChats" : [],
        "email" : "elvin@mail.com",
        "name" : "Elvin",
        "phone" : "1231231421",
        "gender" : "male",
        "password" : "$2b$08$4le6wELFxl0XsfJbJq.eHOOCg.lqwETjkGrt1M6bck8HujpYgdVSy",
    },
    {
        "_id" : "5d1cbf421a804a0b4eb1f384",
        "name" : "Lindsey",
        "email" : "lindsey@gmail.com",
        "birthdate" : "2000-01-15T05:00:00.000Z",
        "password" : "password",
        "phone" : "123-456-7890",
        "gender" : "female",
        "isActive" : false,
        "image" : "me.png",
        "bio" : "Will be filled out later",
        "recentLocation" : null,
        "ignoredChats" : [],
        "acceptedChats" : [],
        "pendingChats" : []
    },
    {
        "_id" : "5d1cbf421a804a0b4eb1f383",
        "name" : "Chase",
        "email" : "chase@gmail.com",
        "birthdate" : "2000-01-15T05:00:00.000Z",
        "password" : "password",
        "phone" : "123-456-7890",
        "gender" : "male",
        "isActive" : false,
        "image" : "me.png",
        "bio" : "Will be filled out later",
        "recentLocation" : null,
        "ignoredChats" : [],
        "acceptedChats" : [],
        "pendingChats" : []
    },
    {
        "_id" : "5d1cbf421a804a0b4eb1f385",
        "name" : "Jenna",
        "email" : "jenna@gmail.com",
        "birthdate" : "2000-01-15T05:00:00.000Z",
        "password" : "password",
        "phone" : "123-456-7890",
        "gender" : "female",
        "isActive" : false,
        "image" : "me.png",
        "bio" : "Will be filled out later",
        "recentLocation" : null,
        "ignoredChats" : [],
        "acceptedChats" : [],
        "pendingChats" : []
    },
    {
        "_id" : "5d1cbf421a804a0b4eb1f386",
        "name" : "Emery",
        "email" : "emery@gmail.com",
        "birthdate" : "2000-01-15T05:00:00.000Z",
        "password" : "password",
        "phone" : "123-456-7890",
        "gender" : "female",
        "isActive" : false,
        "image" : "me.png",
        "bio" : "Will be filled out later",
        "recentLocation" : null,
        "ignoredChats" : [],
        "acceptedChats" : [],
        "pendingChats" : []
    },
    {
        "_id" : "5d1cbf421a804a0b4eb1f387",
        "name" : "Alyssa",
        "email" : "alyssa@gmail.com",
        "birthdate" : "2000-01-15T05:00:00.000Z",
        "password" : "password",
        "phone" : "123-456-7890",
        "gender" : "female",
        "isActive" : false,
        "image" : "me.png",
        "bio" : "Will be filled out later",
        "recentLocation" : null,
        "ignoredChats" : [],
        "acceptedChats" : [],
        "pendingChats" : []
    }
];

export default mongodb;